// <auto-generated />
using System;
using Connectamente.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Connectamente.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406135229_CreatePaciente0604")]
    partial class CreatePaciente0604
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Connectamente.API.Models.ConsultaModel", b =>
                {
                    b.Property<string>("ConsultaId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AnotacoesConsulta")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("DataHoraConsulta")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("DuracaoConsulta")
                        .HasColumnType("time(6)");

                    b.Property<string>("ProntuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PsicologoModelPsicologoId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ConsultaId");

                    b.HasIndex("ProntuarioId");

                    b.HasIndex("PsicologoModelPsicologoId");

                    b.ToTable("Consulta");

                    b.HasData(
                        new
                        {
                            ConsultaId = "c5f41454-0d00-45f5-a00d-1cce66500694",
                            AnotacoesConsulta = "Resumo sessao resumida",
                            DataHoraConsulta = new DateTime(2002, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DuracaoConsulta = new TimeSpan(0, 0, 50, 0, 0),
                            ProntuarioId = "68527bd1-63c9-4ce5-90b7-976fef420d8f"
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.PacienteModel", b =>
                {
                    b.Property<string>("PacienteId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContatoEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HistoricoPaciente")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PsicologoResponsavelId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("PacienteId");

                    b.HasIndex("PsicologoResponsavelId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Paciente");

                    b.HasData(
                        new
                        {
                            PacienteId = "745baf03-ea33-4020-8959-e060cb422ff3",
                            ContatoEmergencia = "14999009858",
                            HistoricoPaciente = "Histórico inicial do paciente para testes de sistema.",
                            PsicologoResponsavelId = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            UsuarioId = "745baf03-ea33-4020-8959-e060cb422ff3"
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.ProntuarioModel", b =>
                {
                    b.Property<string>("ProntuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PacienteId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PsicologoResponsavelId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Queixas")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoProntuario")
                        .HasColumnType("int");

                    b.HasKey("ProntuarioId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("PsicologoResponsavelId");

                    b.ToTable("Prontuario");

                    b.HasData(
                        new
                        {
                            ProntuarioId = "68527bd1-63c9-4ce5-90b7-976fef420d8f",
                            DataCriacao = new DateTime(2002, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataUltimaAtualizacao = new DateTime(2002, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PacienteId = "745baf03-ea33-4020-8959-e060cb422ff3",
                            PsicologoResponsavelId = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            Queixas = "Paciente relata ansiedade e dificuldades para dormir.",
                            TipoProntuario = 1
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.PsicologoModel", b =>
                {
                    b.Property<string>("PsicologoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CRP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("TipoPerfil")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("PsicologoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Psicologo");

                    b.HasData(
                        new
                        {
                            PsicologoId = "59de1fac-5ba6-49b0-8849-c97e3c7ba11b",
                            CRP = "1235545",
                            Descricao = "LET TIME JUST FLYYYYY",
                            TipoPerfil = 1,
                            UsuarioId = "59de1fac-5ba6-49b0-8849-c97e3c7ba11b"
                        },
                        new
                        {
                            PsicologoId = "745baf03-ea33-4020-8959-e060cb422ff3",
                            CRP = "1234555",
                            Descricao = "FOUND MY HOPE AND PRIIIDEEE AGAIIN",
                            TipoPerfil = 3,
                            UsuarioId = "745baf03-ea33-4020-8959-e060cb422ff3"
                        },
                        new
                        {
                            PsicologoId = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            CRP = "12345",
                            Descricao = "REBIRTH OF A MAN",
                            TipoPerfil = 2,
                            UsuarioId = "70f93f27-32b1-4de5-bee3-b0de2cf80047"
                        });
                });

            modelBuilder.Entity("Connectamente.API.Usuario.UsuarioModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("TipoModulo")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5458aee0-71ca-4f08-88e8-0f03d18d6960",
                            DataNascimento = new DateOnly(2002, 4, 1),
                            Email = "estudante@psico.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/estudante.png",
                            LockoutEnabled = true,
                            Nome = "Ana Julia",
                            NormalizedEmail = "ESTUDANTE@PSICO.COM",
                            NormalizedUserName = "ESTUDANTE@PSICO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ9FzXF/zP/9q8m6sF3jKx5T6P6lB6m1z2x3c4v5b6n7m8==",
                            PhoneNumber = "5514920044824",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "15cfe30f-1dac-404e-85e6-02159dbed489",
                            Sobrenome = "Estudante Psicologia",
                            TipoModulo = 1,
                            TwoFactorEnabled = false,
                            UserName = "estudante@psico.com"
                        },
                        new
                        {
                            Id = "59de1fac-5ba6-49b0-8849-c97e3c7ba11b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7cb3541f-0085-4145-b6d7-3e9ae3a300a5",
                            DataNascimento = new DateOnly(2001, 12, 19),
                            Email = "admin@psico.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/admin.png",
                            LockoutEnabled = true,
                            Nome = "Tainara",
                            NormalizedEmail = "ADMIN@PSICO.COM",
                            NormalizedUserName = "ADMIN@PSICO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ9FzXF/zP/9q8m6sF3jKx5T6P6lB6m1z2x3c4v5b6n7m8==",
                            PhoneNumber = "5514988060308",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5b0faad3-6502-4325-94ee-33aab11905d7",
                            Sobrenome = "Administrador Psicologia",
                            TipoModulo = 1,
                            TwoFactorEnabled = false,
                            UserName = "admin@psico.com"
                        },
                        new
                        {
                            Id = "745baf03-ea33-4020-8959-e060cb422ff3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0565c7de-832d-4003-bdd3-5386ff2a214b",
                            DataNascimento = new DateOnly(2001, 7, 13),
                            Email = "clinica@psico.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/clinica.png",
                            LockoutEnabled = true,
                            Nome = "Gallo",
                            NormalizedEmail = "CLINICA@PSICO.COM",
                            NormalizedUserName = "CLINICA@PSICO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ9FzXF/zP/9q8m6sF3jKx5T6P6lB6m1z2x3c4v5b6n7m8==",
                            PhoneNumber = "5514991044050",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ddaeca55-d4a8-40bd-8dce-21df6b31d700",
                            Sobrenome = "Clinica Psicologia",
                            TipoModulo = 2,
                            TwoFactorEnabled = false,
                            UserName = "clinica@psico.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            Name = "Estudante",
                            NormalizedName = "ESTUDANTE"
                        },
                        new
                        {
                            Id = "59de1fac-5ba6-49b0-8849-c97e3c7ba11b",
                            Name = "Coordendor",
                            NormalizedName = "COORDENADOR"
                        },
                        new
                        {
                            Id = "e4e84c5f-3b0a-43f3-951e-f45317d3e7b4",
                            Name = "Clinica",
                            NormalizedName = "CLINICA"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            RoleId = "70f93f27-32b1-4de5-bee3-b0de2cf80047"
                        },
                        new
                        {
                            UserId = "59de1fac-5ba6-49b0-8849-c97e3c7ba11b",
                            RoleId = "59de1fac-5ba6-49b0-8849-c97e3c7ba11b"
                        },
                        new
                        {
                            UserId = "745baf03-ea33-4020-8959-e060cb422ff3",
                            RoleId = "e4e84c5f-3b0a-43f3-951e-f45317d3e7b4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.ConsultaModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.ProntuarioModel", "Prontuario")
                        .WithMany("ConsultasVinculadas")
                        .HasForeignKey("ProntuarioId");

                    b.HasOne("Connectamente.API.Models.PsicologoModel", null)
                        .WithMany("ConsultasAgendadas")
                        .HasForeignKey("PsicologoModelPsicologoId");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.PacienteModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.PsicologoModel", "PsicologoResponsavel")
                        .WithMany()
                        .HasForeignKey("PsicologoResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Usuario.UsuarioModel", "Usuario")
                        .WithOne()
                        .HasForeignKey("Connectamente.API.Models.PacienteModel", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PsicologoResponsavel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.ProntuarioModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.PacienteModel", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.PsicologoModel", "PsicologoResponsavel")
                        .WithMany("Prontuarios")
                        .HasForeignKey("PsicologoResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("PsicologoResponsavel");
                });

            modelBuilder.Entity("Connectamente.API.Models.PsicologoModel", b =>
                {
                    b.HasOne("Connectamente.API.Usuario.UsuarioModel", "Usuario")
                        .WithOne()
                        .HasForeignKey("Connectamente.API.Models.PsicologoModel", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Connectamente.API.Usuario.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Connectamente.API.Usuario.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Usuario.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Connectamente.API.Usuario.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Connectamente.API.Models.ProntuarioModel", b =>
                {
                    b.Navigation("ConsultasVinculadas");
                });

            modelBuilder.Entity("Connectamente.API.Models.PsicologoModel", b =>
                {
                    b.Navigation("ConsultasAgendadas");

                    b.Navigation("Prontuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
