// <auto-generated />
using System;
using Connectamente.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Connectamente.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607214810_ConsolidacaoEstruturaBanco")]
    partial class ConsolidacaoEstruturaBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Connectamente.API.Models.AnamneseAdolescenteModel", b =>
                {
                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("Alimentacao")
                        .HasColumnType("longtext");

                    b.Property<string>("AtitudeMaeFrenteQueixa")
                        .HasColumnType("longtext");

                    b.Property<string>("AtitudeOutrosFamiliares")
                        .HasColumnType("longtext");

                    b.Property<string>("AtitudePaiFrenteQueixa")
                        .HasColumnType("longtext");

                    b.Property<string>("Companheiros")
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoFamiliarNervoso")
                        .HasColumnType("longtext");

                    b.Property<string>("DesdeQuando")
                        .HasColumnType("longtext");

                    b.Property<string>("DesenvolvimentoPsicomotor")
                        .HasColumnType("longtext");

                    b.Property<string>("DificuldadeEscolar")
                        .HasColumnType("longtext");

                    b.Property<string>("Escola")
                        .HasColumnType("longtext");

                    b.Property<string>("Escolaridade")
                        .HasColumnType("longtext");

                    b.Property<string>("FamiliaFazVisitas")
                        .HasColumnType("longtext");

                    b.Property<string>("FamiliaRecebeVisitas")
                        .HasColumnType("longtext");

                    b.Property<string>("FamiliarNervoso")
                        .HasColumnType("longtext");

                    b.Property<string>("FamiliarProblemaMental")
                        .HasColumnType("longtext");

                    b.Property<string>("FoiDesejado")
                        .HasColumnType("longtext");

                    b.Property<string>("Linguagem")
                        .HasColumnType("longtext");

                    b.Property<string>("LocalEstudo")
                        .HasColumnType("longtext");

                    b.Property<string>("QueixaPrincipal")
                        .HasColumnType("longtext");

                    b.Property<string>("QuemEscolheCompanheiros")
                        .HasColumnType("longtext");

                    b.Property<int>("ResponsavelPrincipalId")
                        .HasColumnType("int");

                    b.Property<string>("Sono")
                        .HasColumnType("longtext");

                    b.Property<string>("TiposDiversao")
                        .HasColumnType("longtext");

                    b.Property<string>("Tiques")
                        .HasColumnType("longtext");

                    b.Property<string>("ViciosFamilia")
                        .HasColumnType("longtext");

                    b.HasKey("DocumentoClinicoId");

                    b.HasIndex("ResponsavelPrincipalId");

                    b.ToTable("AnamnesesAdolescente", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.AnamneseAdultoModel", b =>
                {
                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("Afetividade")
                        .HasColumnType("longtext");

                    b.Property<string>("AtencaoTenacidade")
                        .HasColumnType("longtext");

                    b.Property<string>("AtencaoVigilancia")
                        .HasColumnType("longtext");

                    b.Property<string>("Atitude")
                        .HasColumnType("longtext");

                    b.Property<string>("AtitudeEntrevistador")
                        .HasColumnType("longtext");

                    b.Property<string>("ConscienciaDoencaAtual")
                        .HasColumnType("longtext");

                    b.Property<bool>("ConteudoDelirios")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ConteudoFobias")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ConteudoHipocondrias")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ConteudoObsessoes")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ConteudoPensamento")
                        .HasColumnType("longtext");

                    b.Property<string>("ExameAparencia")
                        .HasColumnType("longtext");

                    b.Property<string>("ExameComportamento")
                        .HasColumnType("longtext");

                    b.Property<string>("ExpansaoEu")
                        .HasColumnType("longtext");

                    b.Property<string>("FrequenciaPatologia")
                        .HasColumnType("longtext");

                    b.Property<string>("HipoteseDiagnostica")
                        .HasColumnType("longtext");

                    b.Property<string>("HistoriaInfancia")
                        .HasColumnType("longtext");

                    b.Property<string>("HistoriaPatologicaPregressa")
                        .HasColumnType("longtext");

                    b.Property<string>("HistoricoFamiliarConjuge")
                        .HasColumnType("longtext");

                    b.Property<string>("HistoricoFamiliarFilhos")
                        .HasColumnType("longtext");

                    b.Property<string>("HistoricoFamiliarIrmaos")
                        .HasColumnType("longtext");

                    b.Property<string>("HistoricoFamiliarLar")
                        .HasColumnType("longtext");

                    b.Property<string>("HistoricoFamiliarPais")
                        .HasColumnType("longtext");

                    b.Property<string>("Hobbies")
                        .HasColumnType("longtext");

                    b.Property<string>("Humor")
                        .HasColumnType("longtext");

                    b.Property<string>("InicioPatologia")
                        .HasColumnType("longtext");

                    b.Property<string>("Inteligencia")
                        .HasColumnType("longtext");

                    b.Property<string>("IntensidadePatologia")
                        .HasColumnType("longtext");

                    b.Property<string>("Medicamentos")
                        .HasColumnType("longtext");

                    b.Property<string>("Memoria")
                        .HasColumnType("longtext");

                    b.Property<string>("NegacaoEu")
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacoesOrientacao")
                        .HasColumnType("longtext");

                    b.Property<bool>("OrientacaoAutoIdentificatoria")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OrientacaoCorporal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OrientacaoEspacial")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OrientacaoPatologia")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OrientacaoTemporal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PensamentoAcelerado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PensamentoBloqueio")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PensamentoFuga")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PensamentoProlixo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PensamentoRepeticao")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PensamentoRetardado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PensamentoVelocidade")
                        .HasColumnType("longtext");

                    b.Property<string>("QueixaPrincipal")
                        .HasColumnType("longtext");

                    b.Property<string>("QueixaSecundaria")
                        .HasColumnType("longtext");

                    b.Property<string>("RetracaoEu")
                        .HasColumnType("longtext");

                    b.Property<string>("Rotina")
                        .HasColumnType("longtext");

                    b.Property<string>("Sensopercepcao")
                        .HasColumnType("longtext");

                    b.Property<bool>("SensopercepcaoAlucinacao")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SensopercepcaoNormal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sintomas")
                        .HasColumnType("longtext");

                    b.Property<bool>("TendenciaSuicida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Trabalho")
                        .HasColumnType("longtext");

                    b.Property<string>("TratamentosAnteriores")
                        .HasColumnType("longtext");

                    b.Property<string>("Vicios")
                        .HasColumnType("longtext");

                    b.HasKey("DocumentoClinicoId");

                    b.ToTable("AnamnesesAdulto", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.AnexoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CaminhoArquivo")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnviadoPorUsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Extensao")
                        .HasColumnType("longtext");

                    b.Property<string>("HashArquivo")
                        .HasColumnType("longtext");

                    b.Property<int>("IdDocumentoClinico")
                        .HasColumnType("int");

                    b.Property<string>("MimeType")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeArmazenado")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeOriginal")
                        .HasColumnType("longtext");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EnviadoPorUsuarioId");

                    b.HasIndex("IdDocumentoClinico");

                    b.ToTable("Anexos", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.ApplicationUserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext");

                    b.Property<string>("Crp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Matricula")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.AtendimentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataHoraFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("FaltaJustificada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("ProntuarioId")
                        .HasColumnType("int");

                    b.Property<int>("StatusAtendimento")
                        .HasColumnType("int");

                    b.Property<int>("TipoAtendimento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProntuarioId");

                    b.ToTable("Atendimentos", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.AuditoriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Entidade")
                        .HasColumnType("longtext");

                    b.Property<string>("IP")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int?>("ProntuarioId")
                        .HasColumnType("int");

                    b.Property<string>("RegistroId")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoAcao")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ValoresAntesJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ValoresDepoisJson")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProntuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditorias", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.DocumentoClinicoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtendimentoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CriadoPorUsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataDocumento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ExcluidoLogicamente")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("ProntuarioId")
                        .HasColumnType("int");

                    b.Property<int>("StatusDocumento")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentoClinico")
                        .HasColumnType("int");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProntuarioId");

                    b.ToTable("DocumentosClinicos", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.EvolucaoAtendimentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtendimentoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CriadoPorUsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEvolucao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("TextoEvolucao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("DocumentoClinicoId");

                    b.ToTable("EvolucoesAtendimento", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.InfoFamiliarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("CondicaoConjugal")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("GrauInstrucao")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("longtext");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int?>("Parentesco")
                        .HasColumnType("int");

                    b.Property<string>("Profissao")
                        .HasColumnType("longtext");

                    b.Property<string>("RG")
                        .HasColumnType("longtext");

                    b.Property<bool>("ResponsavelPrincipal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("InfosFamiliares", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.PacienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Escolaridade")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoNascimento")
                        .HasColumnType("longtext");

                    b.Property<int>("FamiliarResponsavelId")
                        .HasColumnType("int");

                    b.Property<string>("Naturalidade")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("longtext");

                    b.Property<string>("Profissao")
                        .HasColumnType("longtext");

                    b.Property<string>("RG")
                        .HasColumnType("longtext");

                    b.Property<string>("Religiao")
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<string>("TelefoneRecado")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FamiliarResponsavelId");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.ProntuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPrimeiraConsulta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroProntuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacoesGerais")
                        .HasColumnType("longtext");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("SituacaoProntuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("Prontuarios", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.TermoAutorizacaoMenorModel", b =>
                {
                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<bool>("AutorizaAtendimentoPsicologico")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AutorizaColetaInformacoes")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CPFResponsavel")
                        .HasColumnType("longtext");

                    b.Property<bool>("CienteDevolutivaMensal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataNascimentoMenorNoTermo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InfoFamiliarId")
                        .HasColumnType("int");

                    b.Property<string>("NomeMenorNoTermo")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<string>("RGResponsavel")
                        .HasColumnType("longtext");

                    b.HasKey("DocumentoClinicoId");

                    b.HasIndex("InfoFamiliarId");

                    b.ToTable("TermosAutorizacaoMenor", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.TermoPsicoterapiaIndividualModel", b =>
                {
                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("Abordagem")
                        .HasColumnType("longtext");

                    b.Property<string>("CidadeCliente")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFimVigencia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInicioVigencia")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DuracaoSessaoMinutos")
                        .HasColumnType("int");

                    b.Property<string>("EstadoCivilCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("FrequenciaSemanal")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeClienteNoTermo")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeEstagiarioNoTermo")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfissaoCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("RGCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("RegraCancelamento")
                        .HasColumnType("longtext");

                    b.Property<string>("RegraFaltas")
                        .HasColumnType("longtext");

                    b.Property<string>("RuaCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("TelefoneCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("TelefoneEstagiario")
                        .HasColumnType("longtext");

                    b.HasKey("DocumentoClinicoId");

                    b.ToTable("TermosPsicoterapiaIndividual", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.TratamentoAnteriorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Internacao")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MotivoInternacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int?>("ProntuarioModelId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTratamento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProntuarioModelId");

                    b.ToTable("TratamentosAnterioresPaciente", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.AnamneseAdolescenteModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.DocumentoClinicoModel", "DocumentoClinico")
                        .WithOne()
                        .HasForeignKey("Connectamente.API.Models.AnamneseAdolescenteModel", "DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.InfoFamiliarModel", "ResponsavelPrincipal")
                        .WithMany()
                        .HasForeignKey("ResponsavelPrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentoClinico");

                    b.Navigation("ResponsavelPrincipal");
                });

            modelBuilder.Entity("Connectamente.API.Models.AnamneseAdultoModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.DocumentoClinicoModel", "DocumentoClinico")
                        .WithOne()
                        .HasForeignKey("Connectamente.API.Models.AnamneseAdultoModel", "DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoClinico");
                });

            modelBuilder.Entity("Connectamente.API.Models.AnexoModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", "EnviadoPorUsuario")
                        .WithMany("AnexosEnviados")
                        .HasForeignKey("EnviadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Connectamente.API.Models.DocumentoClinicoModel", "DocumentoClinico")
                        .WithMany()
                        .HasForeignKey("IdDocumentoClinico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentoClinico");

                    b.Navigation("EnviadoPorUsuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.AtendimentoModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.PacienteModel", "Paciente")
                        .WithMany("Atendimentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.ProntuarioModel", "Prontuario")
                        .WithMany("Atendimentos")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.AuditoriaModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.PacienteModel", "Paciente")
                        .WithMany("Auditorias")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Connectamente.API.Models.ProntuarioModel", "Prontuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Paciente");

                    b.Navigation("Prontuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.DocumentoClinicoModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.AtendimentoModel", "Atendimento")
                        .WithMany("DocumentosClinicos")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", "CriadoPorUsuario")
                        .WithMany("DocumentosCriados")
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Connectamente.API.Models.PacienteModel", "Paciente")
                        .WithMany("DocumentosClinicos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.ProntuarioModel", "Prontuario")
                        .WithMany("DocumentosClinicos")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("Paciente");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.EvolucaoAtendimentoModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.AtendimentoModel", "Atendimento")
                        .WithMany("Evolucoes")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", "CriadoPorUsuario")
                        .WithMany("EvolucoesCriadas")
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Connectamente.API.Models.DocumentoClinicoModel", "DocumentoClinico")
                        .WithMany()
                        .HasForeignKey("DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("DocumentoClinico");
                });

            modelBuilder.Entity("Connectamente.API.Models.InfoFamiliarModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.PacienteModel", "Paciente")
                        .WithMany("Familiares")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Connectamente.API.Models.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("InfoFamiliarModelId")
                                .HasColumnType("int");

                            b1.Property<string>("Bairro")
                                .HasColumnType("longtext")
                                .HasColumnName("EnderecoBairro");

                            b1.Property<string>("CEP")
                                .HasColumnType("longtext")
                                .HasColumnName("EnderecoCep");

                            b1.Property<string>("Cidade")
                                .HasColumnType("longtext")
                                .HasColumnName("EnderecoCidade");

                            b1.Property<string>("Estado")
                                .HasColumnType("longtext")
                                .HasColumnName("EnderecoEstado");

                            b1.Property<string>("Logradouro")
                                .HasColumnType("longtext")
                                .HasColumnName("EnderecoLogradouro");

                            b1.Property<string>("Numero")
                                .HasColumnType("longtext")
                                .HasColumnName("EnderecoNumero");

                            b1.HasKey("InfoFamiliarModelId");

                            b1.ToTable("InfosFamiliares");

                            b1.WithOwner()
                                .HasForeignKey("InfoFamiliarModelId");
                        });

                    b.Navigation("Endereco");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Connectamente.API.Models.PacienteModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.InfoFamiliarModel", "FamiliarResponsavel")
                        .WithMany()
                        .HasForeignKey("FamiliarResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Connectamente.API.Models.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("PacienteModelId")
                                .HasColumnType("int");

                            b1.Property<string>("Bairro")
                                .HasColumnType("longtext")
                                .HasColumnName("EnderecoBairro");

                            b1.Property<string>("CEP")
                                .HasColumnType("longtext")
                                .HasColumnName("EnderecoCep");

                            b1.Property<string>("Cidade")
                                .HasColumnType("longtext")
                                .HasColumnName("EnderecoCidade");

                            b1.Property<string>("Estado")
                                .HasColumnType("longtext")
                                .HasColumnName("EnderecoEstado");

                            b1.Property<string>("Logradouro")
                                .HasColumnType("longtext")
                                .HasColumnName("EnderecoLogradouro");

                            b1.Property<string>("Numero")
                                .HasColumnType("longtext")
                                .HasColumnName("EnderecoNumero");

                            b1.HasKey("PacienteModelId");

                            b1.ToTable("Pacientes");

                            b1.WithOwner()
                                .HasForeignKey("PacienteModelId");
                        });

                    b.Navigation("Endereco");

                    b.Navigation("FamiliarResponsavel");
                });

            modelBuilder.Entity("Connectamente.API.Models.ProntuarioModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.PacienteModel", "Paciente")
                        .WithOne("Prontuario")
                        .HasForeignKey("Connectamente.API.Models.ProntuarioModel", "PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Connectamente.API.Models.TermoAutorizacaoMenorModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.DocumentoClinicoModel", "DocumentoClinico")
                        .WithOne()
                        .HasForeignKey("Connectamente.API.Models.TermoAutorizacaoMenorModel", "DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.InfoFamiliarModel", "InfoFamiliar")
                        .WithMany("TermosAutorizacaoMenor")
                        .HasForeignKey("InfoFamiliarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentoClinico");

                    b.Navigation("InfoFamiliar");
                });

            modelBuilder.Entity("Connectamente.API.Models.TermoPsicoterapiaIndividualModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.DocumentoClinicoModel", "DocumentoClinico")
                        .WithOne()
                        .HasForeignKey("Connectamente.API.Models.TermoPsicoterapiaIndividualModel", "DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoClinico");
                });

            modelBuilder.Entity("Connectamente.API.Models.TratamentoAnteriorModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.PacienteModel", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.ProntuarioModel", "Prontuario")
                        .WithMany("TratamentosAnteriores")
                        .HasForeignKey("ProntuarioModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Paciente");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Connectamente.API.Models.ApplicationUserModel", b =>
                {
                    b.Navigation("AnexosEnviados");

                    b.Navigation("Auditorias");

                    b.Navigation("DocumentosCriados");

                    b.Navigation("EvolucoesCriadas");
                });

            modelBuilder.Entity("Connectamente.API.Models.AtendimentoModel", b =>
                {
                    b.Navigation("DocumentosClinicos");

                    b.Navigation("Evolucoes");
                });

            modelBuilder.Entity("Connectamente.API.Models.InfoFamiliarModel", b =>
                {
                    b.Navigation("TermosAutorizacaoMenor");
                });

            modelBuilder.Entity("Connectamente.API.Models.PacienteModel", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Auditorias");

                    b.Navigation("DocumentosClinicos");

                    b.Navigation("Familiares");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.ProntuarioModel", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Auditorias");

                    b.Navigation("DocumentosClinicos");

                    b.Navigation("TratamentosAnteriores");
                });
#pragma warning restore 612, 618
        }
    }
}
