// <auto-generated />
using System;
using System.Collections.Generic;
using Connectamente.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Connectamente.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Connectamente.API.Models.ApplicationUserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("AssinouTermoResponsabilidadeEstagiario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .IsFixedLength(false);

                    b.Property<string>("Crp")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Matricula")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_AspNetUsers_CPF");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "328b3ebd-50e0-4df8-945e-46540a064859",
                            AccessFailedCount = 0,
                            AssinouTermoResponsabilidadeEstagiario = false,
                            Ativo = true,
                            ConcurrencyStamp = "ef7a1510-9177-4c44-b0cf-5b12da6bf121",
                            Cpf = "12345678901",
                            Crp = "06/12345-6",
                            DataCadastro = new DateTime(2026, 5, 29, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mariana.admin@connectamente.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Matricula = "PR99955",
                            NomeCompleto = "Profª. Dra. Mariana Silva",
                            NormalizedEmail = "MARIANA.ADMIN@CONNECTAMENTE.COM",
                            NormalizedUserName = "MARIANA.ADMIN@CONNECTAMENTE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFIYB3mcgq4GOeMsipzongcd9/NtlcZ6M1Nt3ZS4xbe/fBY27c6LqOVsg65D8K3s4Q==",
                            PhoneNumber = "14999009858",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ef7a1510-9177-4c44-b0cf-5b12da6bf121",
                            TipoUsuario = "Professor",
                            TwoFactorEnabled = false,
                            UserName = "mariana.admin@connectamente.com"
                        },
                        new
                        {
                            Id = "b29fbcde-2222-53c2-c5fb-5c9d1d56ebbb",
                            AccessFailedCount = 0,
                            AssinouTermoResponsabilidadeEstagiario = false,
                            Ativo = true,
                            ConcurrencyStamp = "bc3101aa-2831-4e44-88aa-cc1234567890",
                            Cpf = "98765432100",
                            DataCadastro = new DateTime(2026, 5, 29, 11, 0, 0, 0, DateTimeKind.Utc),
                            Email = "gabriel.aluno@connectamente.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Matricula = "AL202611",
                            NomeCompleto = "Gabriel Soares Santos",
                            NormalizedEmail = "GABRIEL.ALUNO@CONNECTAMENTE.COM",
                            NormalizedUserName = "GABRIEL.ALUNO@CONNECTAMENTE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECqmsN7h3bTCdvve7kCxD4rsONbfTJIkTx6zQLg9xsLKtB+MoWEZ0VcZJjuWlqpMng==",
                            PhoneNumber = "14999193077",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bc3101aa-2831-4e44-88aa-cc1234567890",
                            TipoUsuario = "Aluno",
                            TwoFactorEnabled = false,
                            UserName = "gabriel.aluno@connectamente.com"
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.AtendimentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("DataAtualizacao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<DateTime?>("DataHoraFim")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataHoraInicio")
                        .HasColumnType("datetime");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ProntuarioId")
                        .HasColumnType("int");

                    b.Property<string>("StatusAtendimento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Agendado");

                    b.Property<string>("TipoAtendimento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProntuarioId");

                    b.ToTable("Atendimentos", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.AuditoriaModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime");

                    b.Property<string>("NomeTabela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PacienteModelId")
                        .HasColumnType("int");

                    b.Property<int?>("ProntuarioModelId")
                        .HasColumnType("int");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoAcao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ValoresAntigos")
                        .HasColumnType("longtext");

                    b.Property<string>("ValoresNovos")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PacienteModelId");

                    b.HasIndex("ProntuarioModelId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditorias", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.DocumentoClinicoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtendimentoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("DataAtualizacao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ProntuarioId")
                        .HasColumnType("int");

                    b.Property<string>("TipoDocumentoClinico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioResponsavelId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("ProntuarioId");

                    b.HasIndex("UsuarioResponsavelId");

                    b.ToTable("DocumentosClinicos", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.FamiliarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("DataAtualizacao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Parentesco")
                        .HasColumnType("int");

                    b.Property<int>("ProntuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("ResponsavelPrincipal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TermoAutorizacaoMenor")
                        .HasColumnType("tinyint(1)");

                    b.ComplexProperty<Dictionary<string, object>>("Endereco", "Connectamente.API.Models.FamiliarModel.Endereco#Endereco", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("CEP")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("varchar(8)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("varchar(2)");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Identificacao", "Connectamente.API.Models.FamiliarModel.Identificacao#Identificacao", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CPF")
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)");

                            b1.Property<DateTime>("DataNascimento")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("Email")
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<int>("Escolaridade")
                                .HasColumnType("int");

                            b1.Property<int>("EstadoCivil")
                                .HasColumnType("int");

                            b1.Property<string>("EstadoNascimento")
                                .HasMaxLength(2)
                                .HasColumnType("varchar(2)");

                            b1.Property<int>("Genero")
                                .HasColumnType("int");

                            b1.Property<string>("Naturalidade")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("NomeCompleto")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<string>("Profissao")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("RG")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("Religiao")
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("TelefonePrincipal")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("TelefoneRecado")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProntuarioId");

                    b.ToTable("Familiares", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.PacienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("DataAtualizacao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.ComplexProperty<Dictionary<string, object>>("Endereco", "Connectamente.API.Models.PacienteModel.Endereco#Endereco", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("CEP")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("varchar(8)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("varchar(2)");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Identificacao", "Connectamente.API.Models.PacienteModel.Identificacao#Identificacao", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CPF")
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)");

                            b1.Property<DateTime>("DataNascimento")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("Email")
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<int>("Escolaridade")
                                .HasColumnType("int");

                            b1.Property<int>("EstadoCivil")
                                .HasColumnType("int");

                            b1.Property<string>("EstadoNascimento")
                                .HasMaxLength(2)
                                .HasColumnType("varchar(2)");

                            b1.Property<int>("Genero")
                                .HasColumnType("int");

                            b1.Property<string>("Naturalidade")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("NomeCompleto")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<string>("Profissao")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("RG")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("Religiao")
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("TelefonePrincipal")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("TelefoneRecado")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.ProntuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("DataAtualizacao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<DateTime?>("DataPrimeiraConsulta")
                        .HasColumnType("date");

                    b.Property<string>("NumeroProntuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<string>("PsicologoResponsavelId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SituacaoProntuario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Ativo");

                    b.HasKey("Id");

                    b.HasIndex("NumeroProntuario")
                        .IsUnique()
                        .HasDatabaseName("IX_Prontuarios_NumeroProntuario");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.HasIndex("PsicologoResponsavelId");

                    b.ToTable("Prontuarios", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.TratamentoAnteriorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("DataAtualizacao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<bool>("Internacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("MotivoInternacao")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ProntuarioId")
                        .HasColumnType("int");

                    b.Property<string>("TipoTratamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProntuarioId");

                    b.ToTable("TratamentosAnteriores", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-0001-prof-adm-000000000001",
                            ConcurrencyStamp = "a1b2c3d4-0001-0001-0001-000000000001",
                            Name = "Professor",
                            NormalizedName = "PROFESSOR"
                        },
                        new
                        {
                            Id = "role-0002-aluno-00-000000000002",
                            ConcurrencyStamp = "a1b2c3d4-0002-0002-0002-000000000002",
                            Name = "Aluno",
                            NormalizedName = "ALUNO"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "328b3ebd-50e0-4df8-945e-46540a064859",
                            RoleId = "role-0001-prof-adm-000000000001"
                        },
                        new
                        {
                            UserId = "b29fbcde-2222-53c2-c5fb-5c9d1d56ebbb",
                            RoleId = "role-0002-aluno-00-000000000002"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.AtendimentoModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.ProntuarioModel", "Prontuario")
                        .WithMany("Atendimentos")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.AuditoriaModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.PacienteModel", null)
                        .WithMany("Auditorias")
                        .HasForeignKey("PacienteModelId");

                    b.HasOne("Connectamente.API.Models.ProntuarioModel", null)
                        .WithMany("Auditorias")
                        .HasForeignKey("ProntuarioModelId");

                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", null)
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Connectamente.API.Models.DocumentoClinicoModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.AtendimentoModel", "Atendimento")
                        .WithMany("DocumentosClinicos")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Connectamente.API.Models.ProntuarioModel", "Prontuario")
                        .WithMany("DocumentosClinicos")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", "Usuario")
                        .WithMany("DocumentosCriados")
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Prontuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.FamiliarModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.ProntuarioModel", "Prontuario")
                        .WithMany("Familiares")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.ProntuarioModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.PacienteModel", "Paciente")
                        .WithOne("Prontuario")
                        .HasForeignKey("Connectamente.API.Models.ProntuarioModel", "PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", "PsicologoResponsavel")
                        .WithMany("ProntuariosResponsavel")
                        .HasForeignKey("PsicologoResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Paciente");

                    b.Navigation("PsicologoResponsavel");
                });

            modelBuilder.Entity("Connectamente.API.Models.TratamentoAnteriorModel", b =>
                {
                    b.HasOne("Connectamente.API.Models.ProntuarioModel", "Prontuario")
                        .WithMany("TratamentosAnteriores")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Connectamente.API.Models.ApplicationUserModel", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("DocumentosCriados");

                    b.Navigation("ProntuariosResponsavel");
                });

            modelBuilder.Entity("Connectamente.API.Models.AtendimentoModel", b =>
                {
                    b.Navigation("DocumentosClinicos");
                });

            modelBuilder.Entity("Connectamente.API.Models.PacienteModel", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.ProntuarioModel", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Auditorias");

                    b.Navigation("DocumentosClinicos");

                    b.Navigation("Familiares");

                    b.Navigation("TratamentosAnteriores");
                });
#pragma warning restore 612, 618
        }
    }
}
